# Generated by Django 3.0.4 on 2020-03-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_name',
            field=models.CharField(default='default name', max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.CharField(default='private', max_length=4),
        ),
    ]
