# Generated by Django 3.0.4 on 2020-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2app', '0002_auto_20200320_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.CharField(default='nothing', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.CharField(default='pri', max_length=4),
        ),
    ]
